{
 "title": "ARPANET-INTERNAL",
 "tags": [
  "FluxQL",
  "InfluxDB",
  "NetFlow"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "influxdbsrc", "label": "Source", "query": "influxdb" },
   { "name": "bucket", "label": "Bucket", "query": { "query": "buckets()" } },
   {
    "name": "Measurement",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.measurements(bucket: \"${bucket}\")\n"
    }
   },
   {
    "name": "Router",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n  bucket: \"${bucket}\",\n  tag: \"ROUTER\",\n  start: -30d\n)\n"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 14, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://data.shupogaki.org/assets/1/1c79ac50b06bb42a24058bf13c162a3e-2390019565.gif\">"
   }
  },
  {
   "title": "Top Ports",
   "type": "table",
   "description": "Ports 0 are omitted as they are most likely link layer protocols, like ARP.",
   "gridPos": { "h": 14, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${Measurement}\")\n  |> filter(fn: (r) => r.ROUTER == \"${Router}\")\n  |> filter(fn: (r) => r._field == \"dstPort\")\n  |> filter(fn: (r) => r._value != 0)                 // 👈 omit port 0\n  |> map(fn: (r) => ({ r with port: string(v: r._value) }))\n  |> window(every: inf)\n  |> group(columns: [\"port\"])\n  |> count()\n  |> group()\n  |> sort(columns: [\"_value\"], desc: true)\n  |> limit(n: 13)\n  |> rename(columns: {_value: \"count\"})"
    }
   ]
  },
  {
   "title": "Top destinations",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${Measurement}\")\n  |> filter(fn: (r) => r.ROUTER == \"${Router}\")\n  |> filter(fn: (r) => r._field == \"dstAddr\")\n  |> map(fn: (r) => ({ r with ip: r._value }))\n  |> group(columns: [\"ip\"])\n  |> count()\n  |> sort(columns: [\"_value\"], desc: true)\n  |> limit(n: 10)\n  |> rename(columns: {_value: \"count\"})\n  |> group()\n"
    }
   ]
  },
  {
   "title": "Top talkers",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 17, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${Measurement}\")\n  |> filter(fn: (r) => r.ROUTER == \"${Router}\")\n  |> filter(fn: (r) => r._field == \"srcAddr\")\n  |> map(fn: (r) => ({ r with ip: r._value }))\n  |> group(columns: [\"ip\"])\n  |> count()\n  |> sort(columns: [\"_value\"], desc: true)\n  |> limit(n: 10)\n  |> rename(columns: {_value: \"count\"})\n  |> group()\n"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 13, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${Measurement}\")\n  |> filter(fn: (r) => r.ROUTER == \"${Router}\")\n  |> filter(fn: (r) => r._field == \"outPakt\")     // bytes (IN_OCTETS)\n  |> toFloat()\n  |> sum()\n  |> map(fn: (r) => ({ r with _value: r._value * 8.0 }))  // convert to bits\n  |> rename(columns: {_value: \"total_bits\"})\n  |> group()\n"
    }
   ]
  },
  {
   "title": "Geomap",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 15, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${Measurement}\")\n  |> filter(fn: (r) => r.ROUTER == \"${Router}\")\n  |> filter(fn: (r) => r._field == \"dstCntr\")\n  |> map(fn: (r) => ({ r with location: r._value }))  // materialize _value to location\n  |> group(columns: [\"location\"])\n  |> count()\n  |> rename(columns: {_value: \"value\"})\n  |> group()\n"
    }
   ]
  },
  {
   "title": "Top Protocols",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 15, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"${Measurement}\")\n  |> filter(fn: (r) => r.ROUTER == \"${Router}\")\n  |> group(columns: [\"proto\"])\n  |> count()\n  |> keep(columns: [\"proto\", \"_value\"])\n  |> rename(columns: {_value: \"\"})\n"
    }
   ]
  }
 ]
}