version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-test
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    restart: unless-stopped
    networks:
      - db

  influxdb:
    image: influxdb:2.7
    container_name: influxdb-test  
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=yuru
      - DOCKER_INFLUXDB_INIT_PASSWORD=2214112137
      - DOCKER_INFLUXDB_INIT_ORG=staging
      - DOCKER_INFLUXDB_INIT_BUCKET=STAGING-NETFLOW
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=2214112137
    volumes:
      - ./influxdb_data:/var/lib/influxdb2
    restart: unless-stopped
    networks:
      - db

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    volumes:
      - ./grafana-storage:/var/lib/grafana
    depends_on:
      - influxdb
    networks:
      - db

networks:
  db:
    driver: bridge
